# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quiz.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(626, 708)
        icon = QtGui.QIcon()
        # Ensure this path is correct and the image exists
        icon.addPixmap(QtGui.QPixmap("../../../../Users/DELL/Desktop/craps/qz.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QToolBox::tab,\n"
"QPushButton,\n"
"QLabel,\n"
"QplaintextEdit,\n"
"QRadioButton,\n"
"QStatusBar,\n"
"{\n"
"font-family:system-ui;\n"
"font-size:14px;\n"
"}\n"
"#tittle_frame{\n"
"background-color:#393e4d;\n"
"}\n"
"\n"
"#tittle_frame QLabel{\n"
"font-family: Zurich XBIK BT;\n"
"font-size:30px;\n"
"color:#fff;\n"
"}\n"
"QToolBoxButton{\n"
"min-height:35px;\n"
"}\n"
"QToolBox::tab{\n"
"background:qlineargradient(x1:0,y1:0,x2:0,y2:1,\n"
"stop:0#a6a29a,stop:0.4#DDDDDD,\n"
"stop:0.6 #D8D8D8,stop:1.0 #a6a29a);\n"
"padding:0.10px;\n"
"}\n"
"QToolBox::tab:selected{\n"
"font: italic;\n"
"font-weight:600;\n"
"}\n"
"QLabel{\n"
"border-radiu:3px;\n"
"padding:5px;\n"
"color:#0a3622;\n"
"min-height:20px;\n"
"\n"
"}\n"
"QcomboBox, QspinBox, QLineEdit{\n"
"min-height:20px;\n"
"padding:5px;\n"
"font-family: Times New Roman;\n"
"font-size:14px;\n"
"color:#3232CD;\n"
"}\n"
"QPushButton {\n"
"    padding: 10px;\n"
"    border-top-right-radius: 10px 15px; /* Using single values for simplicity as multi-value might be interpreted differently */\n"
"    border-top-left-radius: 5px;\n"
"    border-bottom-left-radius: 10px  15px;\n"
"    border-bottom-right-radius: 5px;\n"
"    max-width: 200px;\n"
"    background-color: #2d6df4;\n"
"    font-weight: bold; /* Changed to \'bold\' for clearer compatibility */\n"
"    color: #fff;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(20, 100, 581, 531))
        self.toolBox.setObjectName("toolBox")
        self.widget = QtWidgets.QWidget()
        self.widget.setGeometry(QtCore.QRect(0, 0, 581, 461))
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.db_frame = QtWidgets.QFrame(self.widget)
        self.db_frame.setFrameShape(QtWidgets.QFrame.StyledPanel) # Corrected: QtWidgets.QFrame.StyledPanel
        self.db_frame.setFrameShadow(QtWidgets.QFrame.Raised) # Corrected: QtWidgets.QFrame.Raised
        self.db_frame.setObjectName("db_frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.db_frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_14 = QtWidgets.QLabel(self.db_frame)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.spinBox_2 = QtWidgets.QSpinBox(self.db_frame)
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(20)
        self.spinBox_2.setProperty("value", 20)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_2.addWidget(self.spinBox_2)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.db_frame)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.comboBox_6 = QtWidgets.QComboBox(self.db_frame)
        self.comboBox_6.setObjectName("comboBox_6")
        self.horizontalLayout_4.addWidget(self.comboBox_6)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)

        # Removed the problematic fixed-size spacers and adjusted row index
        self.frame_2 = QtWidgets.QFrame(self.db_frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel) # Corrected: QtWidgets.QFrame.StyledPanel
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised) # Corrected: QtWidgets.QFrame.Raised
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 0, 0, 1, 1)
        # Changed row index for frame_2 to 2, as the previous spacer at row 2 is removed
        self.gridLayout_4.addWidget(self.frame_2, 2, 0, 1, 1)

        # ADDED: An expanding vertical spacer to push content to the top if needed
        # This replaces the large fixed spacers removed from the .ui
        self.gridLayout_4.addItem(QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding), 3, 0, 1, 1)

        # Set row stretches for gridLayout_4 to ensure rows expand
        # Give content rows a small stretch (e.g., 1) and the spacer a larger stretch (e.g., 10)
        # This ensures content is visible and the spacer takes up remaining space.
        self.gridLayout_4.setRowStretch(0, 1) # For "Number of Questions"
        self.gridLayout_4.setRowStretch(1, 1) # For "Select Category"
        self.gridLayout_4.setRowStretch(2, 1) # For "Get New Question" button
        self.gridLayout_4.setRowStretch(3, 10) # This is the new spacer, let it expand significantly


        self.gridLayout_3.addWidget(self.db_frame, 0, 0, 1, 1)
        self.toolBox.addItem(self.widget, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 551, 421))
        self.page_2.setObjectName("page_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.question_frame = QtWidgets.QFrame(self.page_2)
        self.question_frame.setFrameShape(QtWidgets.QFrame.StyledPanel) # Corrected: QtWidgets.QFrame.StyledPanel
        self.question_frame.setFrameShadow(QtWidgets.QFrame.Raised) # Corrected: QtWidgets.QFrame.Raised
        self.question_frame.setObjectName("question_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.question_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.info_frame = QtWidgets.QFrame(self.question_frame)
        self.info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel) # Corrected: QtWidgets.QFrame.StyledPanel
        self.info_frame.setFrameShadow(QtWidgets.QFrame.Raised) # Corrected: QtWidgets.QFrame.Raised
        self.info_frame.setObjectName("info_frame")
        self.question_count_label = QtWidgets.QLabel(self.info_frame)
        self.question_count_label.setGeometry(QtCore.QRect(725, 12, 38, 20))
        self.question_count_label.setAlignment(QtCore.Qt.AlignCenter) # Corrected: QtCore.Qt.AlignCenter
        self.question_count_label.setObjectName("question_count_label")
        self.widget1 = QtWidgets.QWidget(self.info_frame)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.widget1)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.lineEdit = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout_3.addWidget(self.info_frame)
        self.questions_frame = QtWidgets.QFrame(self.question_frame)
        self.questions_frame.setFrameShape(QtWidgets.QFrame.StyledPanel) # Corrected: QtWidgets.QFrame.StyledPanel
        self.questions_frame.setFrameShadow(QtWidgets.QFrame.Raised) # Corrected: QtWidgets.QFrame.Raised
        self.questions_frame.setObjectName("questions_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.questions_frame)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.questions_frame)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.questions_frame)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_2.addWidget(self.plainTextEdit)
        self.answer_frame = QtWidgets.QFrame(self.questions_frame)
        self.answer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel) # Corrected: QtWidgets.QFrame.StyledPanel
        self.answer_frame.setFrameShadow(QtWidgets.QFrame.Raised) # Corrected
        self.answer_frame.setObjectName("answer_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.answer_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.answer_frame)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.answer_frame)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.verticalLayout_2.addWidget(self.answer_frame)
        self.verticalLayout_3.addWidget(self.questions_frame)
        spacerItem2 = QtWidgets.QSpacerItem(20, 51, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.function_frame = QtWidgets.QFrame(self.question_frame)
        self.function_frame.setFrameShape(QtWidgets.QFrame.StyledPanel) # Corrected: QtWidgets.QFrame.StyledPanel
        self.function_frame.setFrameShadow(QtWidgets.QFrame.Raised) # Corrected: QtWidgets.QFrame.Raised
        self.function_frame.setObjectName("function_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.function_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.function_frame)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.function_frame)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.function_frame)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.verticalLayout_3.addWidget(self.function_frame)
        self.gridLayout_5.addWidget(self.question_frame, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_2, "")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 10, 591, 70))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel) # Corrected: QtWidgets.QFrame.StyledPanel
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised) # Corrected: QtWidgets.QFrame.Raised
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem3 = QtWidgets.QSpacerItem(315, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMaximumSize(QtCore.QSize(100, 50))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Documents/pz.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(315, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 0, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 626, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Quiz"))
        self.label_14.setText(_translate("MainWindow", "Number of Questions"))
        self.label_11.setText(_translate("MainWindow", "Select Category"))
        self.pushButton_4.setText(_translate("MainWindow", "Get New Question"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.widget), _translate("MainWindow", "Settings"))
        self.question_count_label.setText(_translate("MainWindow", "10/20"))
        self.label_7.setText(_translate("MainWindow", "Category"))
        self.label_10.setText(_translate("MainWindow", "Questions:"))
        self.radioButton.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_2.setText(_translate("MainWindow", "RadioButton"))
        self.pushButton.setText(_translate("MainWindow", "Try Again"))
        self.pushButton_2.setText(_translate("MainWindow", "Check"))
        self.pushButton_3.setText(_translate("MainWindow", "Next"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Question"))
        self.label_3.setText(_translate("MainWindow", "Quizz!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
